### ISSUE TITLE
possible error in diagKronSum ?

### ISSUE THREAD

**Issue by grero** [gamaleldin/TME#1]
I was looking the diagKronSum function for computing the kronecker sum of diagonal matrices, and it seems the result doesn't agree with what I get when I compute the kronecker sum the straight-forward way.

```matlab
A = diag([1,2,3]);
B = diag([4,5,6,7]);
q1 = diag(kron(A, eye(size(B))) + kron(eye(size(A)), B))
q1 =
    5
    6
    7
    8
    6
    7
    8
    9
    7
    8
    9
   10

q2 = diagKronSum({diag(A),diag(B)})
q2 =

    5
    6
    7
    6
    7
    8
    7
    8
    9
    8
    9
   10

find(q1!=q2)
ans =

   4
   5
   6
   7
   8
   9
```

**Comment by gamaleldin** [comment]
Thank you for your question. The function is correct. 
The confusion here is coming from the fact that the function reverses the order of summation (see the function documentation). In other words, if you send an input list of [A, B] then the function computes B \kronsum A (NOT A \kronsum B). 
I chose the reverse order because the form of the max entropy distribution has this reverse order (see paper methods where T, N, C dimensions order reflects Kronecker summation order of C,N,T).

**Comment by gamaleldin** [comment]
Thank you for your question. The function is correct. 
The confusion here is coming from the fact that the function reverses the order of summation (see the function documentation). In other words, if you send an input list of [A, B] then the function computes B \kronsum A (NOT A \kronsum B). 
I chose the reverse order because the form of the max entropy distribution has this reverse order (see paper methods where T, N, C dimensions order reflects Kronecker summation order of C,N,T).

**Comment by grero** [comment]
Ah Ok, that makes sense. Thanks for the clarification!
